volumes:
  maven-repo:


services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  api-gateway:
    depends_on:
    - redis
    - downstream-service
    - postgres
    
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8080:8080"

    volumes:
      - ./application.yml:/app/application.yml

      - maven-repo:/root/.m2

    restart: unless-stopped


  downstream-service:
    build: ./DownStream-Service
    container_name: downstream_service
    ports:
      - "8081:8080"

    volumes:
      - maven-repo:/root/.m2

    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: gatewaydb
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: unless-stopped

