spring:
  application:
    name: api_gateway

  data:
    redis:
      host: redis
      port: 6379
      database: 0
      timeout: 2s
      client-type: lettuce
      connect-timeout: 2s

resilience4j:
  circuitbreaker:
    instances:
      downstreamService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

  retry:
    instances:
      downstreamRetry:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
