spring:
  application:
    name: api_gateway

  data:
    redis:
      host: redis
      port: 6379
      database: 0
      timeout: 500ms
      client-type: lettuce
      connect-timeout: 500ms

  datasource:
    url: jdbc:postgresql://postgres:5432/gatewaydb
    username: gateway
    password: secret
    hikari:
      connection-timeout: 500
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

resilience4j:
  circuitbreaker:
    instances:
      redis:
        failure-rate-threshold: 1
        wait-duration-in-open-state: 5s
        sliding-window-size: 2
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 1
        automatic-transition-from-open-to-half-open-enabled: true
      downstreamService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
      database:
        failure-rate-threshold: 1
        wait-duration-in-open-state: 5s
        sliding-window-size: 2
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 1
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      downstreamRetry:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException

management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.5,0.95,0.99
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
