apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resilient-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vaibhav979/resilient-api-gateway
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
